@startuml uc_p1

skinparam ArrowThickness 1.25

skinparam ActorBorderThickness 1.5
skinparam ActorBackgroundColor #FEFECE
skinparam ActorBorderColor #B20842

skinparam UsecaseBorderColor #B20842
skinparam UsecaseBorderThickness 1.25
skinparam UsecaseBackgroundColor #FEFECE

skinparam Shadowing true
skinparam dpi 200

' -----------------------------------------------

actor "User" as User

usecase "Sign In" as SignIn
usecase "Sign Up" as SignUp

usecase "View my profile" as ViewMyProfile
usecase "Edit my profile" as EditMyProfile
usecase "Upload image" as UploadImage
usecase "Delete my profile" as DeleteMyProfile

usecase "View mates" as ViewMates
usecase "Chat with a mate" as ChatWithMate
usecase "View mates' requests" as ViewMatesReqs
usecase "Accept/Cancel\na mate's request" as AccCanMateReq

usecase "View an expanded\nuser's profile" as ViewExpandedUserProfile

' see uc2.wsd diagram...
usecase "Go geo chat" as GoGeoChat #LightGreen

' -----------------------------------------------

left to right direction

User --> SignIn
User --> SignUp

User --> ViewMyProfile
ViewMyProfile <-u- EditMyProfile : <<extend>>
ViewMyProfile <-u- DeleteMyProfile : <<extend>>
EditMyProfile <-u- UploadImage : <<extend>>

User -u-> ViewMates
User -d-> ViewMatesReqs

ViewMates <-- ChatWithMate : <<extend>>
ViewMatesReqs <-- AccCanMateReq : <<extend>>
ViewMatesReqs <-- ViewExpandedUserProfile : <<extend>>

User -u-> GoGeoChat

@enduml