
# deploy and run!

run-app:

run-with-app:

run-all:


# release?

local-build:
	go build -ldflags="-s -w" -o ./cmd/main.exe ./cmd/main.go

# can't put a space after "release"!
local-run: local-build
	set GIN_MODE=release&& \
	set HTTP_HOST=0.0.0.0&& \
	set HTTP_PORT=57001&& \
	 "./cmd/main.exe"

# debug?

local-build-debug:
	go build -o ./cmd/main.exe ./cmd/main.go

local-debug: local-build-debug
	set GIN_MODE=debug&& "./cmd/main.exe"

