@startuml delete_user

!include styles.wsd

' -----------------------------------------------

actor "User" as user
boundary "Client App" as clientApp
control "Confirmation\nWindow" as confWindow
participant "Http Server" as httpServer
entity "Domain\nStorage" as domainStorage

' -----------------------------------------------

ref over user, clientApp
SignIn
end ref

user -> clientApp : "Delete Profile"\nbutton pressed
create confWindow
clientApp -> confWindow : display

confWindow --> user
user -> confWindow : "Ok"\nbutton pressed
confWindow --> clientApp : return\npositive status
destroy confWindow

clientApp -> httpServer : send request\n"DELETE /api/my-profile"
httpServer -> httpServer : validate request
httpServer -> httpServer : identify the user

group Transaction (for this user)
    httpServer -> domainStorage : add to deleted list

    httpServer -> domainStorage : delete outgoing\nmate requests
    httpServer -> domainStorage : delete mate chats
    httpServer -> domainStorage : delete mates

    httpServer -> domainStorage : change username\nto "deleted_<uuid>"
    httpServer -> domainStorage : set an avatar\nfor deleted users

    httpServer -> domainStorage : reset hashes\n(password and refresh token)
    httpServer -> domainStorage : reset "hit-me-up" in options
    httpServer -> domainStorage : reset "description" in details
end

httpServer --> clientApp : return sttus\n"HTTP 200 OK"
clientApp -> clientApp : exit to entry window
clientApp --> user

@enduml