@startuml styles

!$line_thickness = 2
!$border_color = "#A61E3B"
!$background_color = "#F6F6C8"

' -----------------------------------------------

skinparam Dpi 250
skinparam Shadowing True
skinparam ArrowThickness $line_thickness

skinparam ActorBackgroundColor $background_color
skinparam ActorBorderColor $border_color
skinparam ActorBorderThickness $line_thickness

skinparam EntityBackgroundColor $background_color
skinparam EntityBorderColor $border_color
skinparam EntityBorderThickness $line_thickness

skinparam BoundaryBackgroundColor $background_color
skinparam BoundaryBorderColor $border_color
skinparam BoundaryBorderThickness $line_thickness

skinparam ControlBackgroundColor $background_color
skinparam ControlBorderColor $border_color
skinparam ControlBorderThickness $line_thickness

skinparam ParticipantBackgroundColor $background_color
skinparam ParticipantBorderColor $border_color
skinparam ParticipantBorderThickness $line_thickness

' -----------------------------------------------

hide footbox

@enduml