FROM golang:1.22.3-alpine3.19 AS build

ENV GOOS linux
ENV CGO_ENABLED 0

WORKDIR /app
COPY geoqq_ws geoqq_ws
COPY common common

WORKDIR /app/geoqq_ws
RUN go build -ldflags="-s -w" -o ./cmd/main ./cmd/main.go

FROM alpine:3.19

COPY --from=build /app/geoqq_ws/internal/config/default.yaml /app/cmd/default.yaml

# Executable File...
COPY --from=build /app/geoqq_ws/cmd/main /app/cmd/main

WORKDIR /app/cmd
CMD ./main